package cards;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.stream.IntStream;

/**
*
* @author ramareddy
*/
public class DeckOfCardsTest {
	@Test
	public void PrintAllDeck() {
		DeckOfCards deck = new DeckOfCards();
		deck.shuffle();
		// print all cards
		IntStream.range(0, 52).forEach(number -> {
			System.out.println(deck.dealOneCard().get());

		});
	}

	// Making sure initial deck and after shuffiling number of cards are same
	@Test
	public void testInitalDeckAndShuffleMatch() {
		DeckOfCards deck = new DeckOfCards();
		int initialDeckSize = deck.getDeckSize();
		deck.shuffle();
		
		int AfterDeckShuffleSize = deck.getDeckSize();

		assertEquals(initialDeckSize, AfterDeckShuffleSize);
	}
	@Test
	public void test53rdCard() {
		DeckOfCards deck = new DeckOfCards();
		deck.shuffle();
		// print all cards
		IntStream.range(0, 52).forEach(number -> {
			deck.dealOneCard();

		});
		assertFalse(deck.dealOneCard().isPresent());

	}
}
